
services:
  api:
    container_name: afm-api
    build:
      args:
        APP_NAME: ${APP_NAME}
        ENTRYPOINT: ${API_ENTRYPOINT}
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: afm-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
