import { ModelAttributes, Model, DataTypes, InitOptions, Sequelize } from "sequelize";
import { BaseModel } from "../util/common";

/**
 * Represents the table generated by a many-to-many association.
 */
export class OrderFood extends BaseModel {
    declare quantity: number;

    /**
     * Performs associations initialization for this model.
     */
    public associate() {
    }

    /**
     * Gets the model attributes.
     * @returns Sequelize initialization model attributes
     */
    public getModelAttributes(): ModelAttributes<Model> {
        return {
            quantity: {
                type: DataTypes.REAL, 
                allowNull: false, 
                validate: {
                    isPositive(x: number) {
                        if(x <= 0) {
                            throw new Error('food quantity must be positive');
                        }
                    }
                }
            }, 
        };
    }

    /**
     * Gets the model initialization options.
     * @param sequelize - The database connection
     * @returns Sequelize model InitOptions
     */
    public getModelInitOptions(sequelize: Sequelize): InitOptions {
        return {
            sequelize: sequelize, 
            modelName: 'OrderFoods', 
        }
    }
}
